channel_url: https://meshtastic.org/e/#CgcSAQE6AgggEgwIATgBQANIAVAeaAE
config:
  bluetooth:
    enabled: true
    fixedPin: 123456
  device:
    nodeInfoBroadcastSecs: 10800
    serialEnabled: true
  display:
    screenOnSecs: 600
  lora:
    hopLimit: 3
    region: US
    sx126xRxBoostedGain: true
    txEnabled: true
    txPower: 30
    usePreset: true
  network:
    ntpServer: meshtastic.pool.ntp.org
  position:
    broadcastSmartMinimumDistance: 100
    broadcastSmartMinimumIntervalSecs: 30
    gpsMode: NOT_PRESENT
    gpsUpdateInterval: 120
    positionBroadcastSecs: 900
    positionBroadcastSmartEnabled: true
    positionFlags: 811
  power:
    lsSecs: 300
    minWakeSecs: 10
    sdsSecs: 4294967295
    waitBluetoothSecs: 60
  security:
    privateKey: base64:EOuaS/Ptf5Lu60p6oxglMwzLnV/cbjZb6o6JkF2+dGc=
    publicKey: base64:BLT1YE3Ep4ynISIKWCe5ueSfkkiF5H/hQTDWLv2XLFg=
    serialEnabled: true
module_config:
  ambientLighting:
    blue: 152
    current: 10
    green: 56
    red: 61
  detectionSensor:
    detectionTriggerType: LOGIC_HIGH
    minimumBroadcastSecs: 45
  mqtt:
    address: mqtt.meshtastic.org
    encryptionEnabled: true
    password: large4cats
    root: msh/US
    username: meshdev
owner: Meshtastic 3898
owner_short: '3898'